#include "../../libjobject/Metadata.h"
#include "test.h"

REFLECT_TYPE_START(Test)
	CONSTRUCTOR(Test, int)
	CONSTRUCTOR(Test, const char*)
	CONSTRUCTOR(Test, int, std::vector<int>)

	FIELD(a)
	FIELD(myString)
	FIELD(ptrString)
	FIELD(vec1)

	METHOD(foo1)
	METHOD(foo2)

	METHOD(int, fooOverloaded, int)
	METHOD(int, fooOverloaded, float)
	METHOD(int, fooOverloaded, std::vector<int>, int)
	METHOD(fooConst)
	METHOD(bar1)
	METHOD(bar2)
	METHOD(bar3)
	METHOD(bar4)
	METHOD(bar5)
	METHOD(bar6)
	METHOD(bar7)
	METHOD(bar8)

	METHOD(fcn1)
	METHOD(fcn2)
	METHOD(fcn3)
	METHOD(fcn4)
	METHOD(fcn5)
	METHOD(fcn6)
	METHOD(fcn7)
	METHOD(fcn8)

	METHOD(fcn9)
	METHOD(fcn10)
	METHOD(fcn11)
	METHOD(fcn12)
	METHOD(fcn13)
	METHOD(fcn14)
	METHOD(fcn15)
	METHOD(fcn16)

	METHOD(fcn17)
	METHOD(fcn18)
	METHOD(fcn19)
	METHOD(fcn20)
	METHOD(fcn21)
	METHOD(fcn22)
	METHOD(fcn23)
	METHOD(fcn24)

	METHOD(bar9)
	METHOD(bar10)
	METHOD(bar11)
	METHOD(bar12)
	METHOD(bar13)
	METHOD(bar14)
	METHOD(bar15)
	METHOD(bar16)
	METHOD(void, bar17)
	METHOD(bar18)
	METHOD(bar19)
	METHOD(bar20)
	METHOD(bar21)
	METHOD(bar22)
	METHOD(bar23)
	METHOD(bar24)
	METHOD(void, overload, int)
	METHOD(void, overloadEx, int)
	METHOD(testPerformance)
REFLECT_TYPE_END

REFLECT_TYPE_START(TestDerived, Test)
	METHOD(fooOverloaded)
	METHOD(fooMarshal1)
REFLECT_TYPE_END
