#include "Parser.h"
#include "../../libjobject/Metadata.h"

REFLECT_CLASS_START(Parser, IParser)
REFLECT_CLASS_END(Parser)

REFLECT_CLASS_REGISTRY_START
	REFLECT_REGISTER_CLASS(Parser)
REFLECT_CLASS_REGISTRY_END

