#include "Parser.h"
#include "../../libjobject/Metadata.h"

REFLECT_TYPE_START(Parser, IParser)
REFLECT_TYPE_END

REFLECT_CLASS_REGISTRY_START
	REFLECT_REGISTER_CLASS(Parser)
REFLECT_CLASS_REGISTRY_END

