#include "metadata.h"
#include "test.h"



REFLECT_CLASS_START(Test)
	REFLECT_FIELD(a)
	REFLECT_FIELD(myString)
	REFLECT_FIELD(ptrString)
	REFLECT_FIELD(vec1)
	REFLECT_METHOD2(Foo1)
	REFLECT_METHOD2(Foo2)

	REFLECT_METHOD2(FooOverloaded, int, int)
	REFLECT_METHOD2(FooOverloaded, int, float)
	REFLECT_METHOD2(FooOverloaded, int, std::vector<int>)
	REFLECT_METHOD2(FooConst)
	REFLECT_METHOD2(Bar1)
	REFLECT_METHOD2(Bar2)
	REFLECT_METHOD2(Bar3)
	REFLECT_METHOD2(Bar4)
	REFLECT_METHOD2(Bar5)
	REFLECT_METHOD2(Bar6)
	REFLECT_METHOD2(Bar7)
	REFLECT_METHOD2(Bar8)

	REFLECT_METHOD2(Fcn1)
	REFLECT_METHOD2(Fcn2)
	REFLECT_METHOD2(Fcn3)
	REFLECT_METHOD2(Fcn4)
	REFLECT_METHOD2(Fcn5)
	REFLECT_METHOD2(Fcn6)
	REFLECT_METHOD2(Fcn7)
	REFLECT_METHOD2(Fcn8)

	REFLECT_METHOD2(Fcn9)
	REFLECT_METHOD2(Fcn10)
	REFLECT_METHOD2(Fcn11)
	REFLECT_METHOD2(Fcn12)
	REFLECT_METHOD2(Fcn13)
	REFLECT_METHOD2(Fcn14)
	REFLECT_METHOD2(Fcn15)
	REFLECT_METHOD2(Fcn16)

	REFLECT_METHOD2(Fcn17)
	REFLECT_METHOD2(Fcn18)
	REFLECT_METHOD2(Fcn19)
	REFLECT_METHOD2(Fcn20)
	REFLECT_METHOD2(Fcn21)
	REFLECT_METHOD2(Fcn22)
	REFLECT_METHOD2(Fcn23)
	REFLECT_METHOD2(Fcn24)



	REFLECT_METHOD2(Bar9)
	REFLECT_METHOD2(Bar10)
	REFLECT_METHOD2(Bar11)
	REFLECT_METHOD2(Bar12)
	REFLECT_METHOD2(Bar13)
	REFLECT_METHOD2(Bar14)
	REFLECT_METHOD2(Bar15)
	REFLECT_METHOD2(Bar16)
	REFLECT_METHOD2(Bar17, void)
	REFLECT_METHOD2(Bar18)
	REFLECT_METHOD2(Bar19)
	REFLECT_METHOD2(Bar20)
	REFLECT_METHOD2(Bar21)
	REFLECT_METHOD2(Bar22)
	REFLECT_METHOD2(Bar23)
	REFLECT_METHOD2(Bar24)
	REFLECT_METHOD2(Overload, void, int)
	REFLECT_METHOD2(OverloadEx, void, int) 
REFLECT_CLASS_END(Test)

REFLECT_CLASS_START(TestDerived)
	REFLECT_METHOD2(FooOverloaded)
REFLECT_CLASS_END(TestDerived)

REFLECT_FACTORY_START
	REFLECT_CLASS(Test)
REFLECT_FACTORY_END
