#include "metadata.h"
#include "test.h"



REFLECT_CLASS_START(Test)
	REFLECT_FIELD(a)
	REFLECT_FIELD(myString)
	REFLECT_FIELD(ptrString)
	REFLECT_METHOD(Foo1)
	REFLECT_METHOD2(Foo1)

	REFLECT_METHOD(Foo2)
	REFLECT_METHOD2(Foo2)

	REFLECT_METHOD(FooOverloaded, int, int)
	REFLECT_METHOD(FooOverloaded, int, float)
	REFLECT_METHOD(FooOverloaded, int, std::vector<int>)
	REFLECT_METHOD(FooConst)
	REFLECT_METHOD(Bar1)
	REFLECT_METHOD(Bar2)
	REFLECT_METHOD(Bar3)
	REFLECT_METHOD(Bar4)
	REFLECT_METHOD(Bar5)
	REFLECT_METHOD(Bar6)
	REFLECT_METHOD(Bar7)
	REFLECT_METHOD(Bar8)

	REFLECT_METHOD2(Fcn1)
	REFLECT_METHOD2(Fcn2)
	REFLECT_METHOD2(Fcn3)
	REFLECT_METHOD2(Fcn4)
	REFLECT_METHOD2(Fcn5)
	REFLECT_METHOD2(Fcn6)
	REFLECT_METHOD2(Fcn7)
	REFLECT_METHOD2(Fcn8)

	REFLECT_METHOD2(Fcn9)
	REFLECT_METHOD2(Fcn10)
	REFLECT_METHOD2(Fcn11)
	REFLECT_METHOD2(Fcn12)
	REFLECT_METHOD2(Fcn13)
	REFLECT_METHOD2(Fcn14)
	REFLECT_METHOD2(Fcn15)
	REFLECT_METHOD2(Fcn16)

	REFLECT_METHOD2(Fcn17)
	REFLECT_METHOD2(Fcn18)
	REFLECT_METHOD2(Fcn19)
	REFLECT_METHOD2(Fcn20)
	REFLECT_METHOD2(Fcn21)
	REFLECT_METHOD2(Fcn22)
	REFLECT_METHOD2(Fcn23)
	REFLECT_METHOD2(Fcn24)



	REFLECT_METHOD(Bar9)
	REFLECT_METHOD(Bar10)
	REFLECT_METHOD(Bar11)
	REFLECT_METHOD(Bar12)
	REFLECT_METHOD(Bar13)
	REFLECT_METHOD(Bar14)
	REFLECT_METHOD(Bar15)
	REFLECT_METHOD(Bar16)
	REFLECT_METHOD(Bar17, void)
	REFLECT_METHOD(Bar18)
	REFLECT_METHOD(Bar19)
	REFLECT_METHOD(Bar20)
	REFLECT_METHOD(Bar21)
	REFLECT_METHOD(Bar22)
	REFLECT_METHOD(Bar23)
	REFLECT_METHOD(Bar24)
	REFLECT_METHOD(Overload, void, int)
	REFLECT_METHOD(OverloadEx, void, int) 
REFLECT_CLASS_END(Test)

REFLECT_CLASS_START(TestDerived)
	REFLECT_METHOD(FooOverloaded)
REFLECT_CLASS_END(TestDerived)

REFLECT_FACTORY_START
	REFLECT_CLASS(Test)
REFLECT_FACTORY_END
